config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users
    resources :rooms,only: [:create, :show]
    resources :messages, only: [:create]
    root to: "homes#top"
    get "home/about"=>"homes#about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships,only: [:create, :destroy]
    get 'followings' => 'users#followings', as: 'followings'
    get 'followers' => 'users#followers', as: 'followers'
  end
   get "search" => "searches#search"
   get 'search_tag' => 'books#search_tag'
    
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  def favorited_by?(uesr)
    favorites.exists?(user_id: user.id)
  end
  has_many :favorited_users,through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  acts_as_taggable_on :tags
  scope :created_within_week, -> {
  where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day)
}

  scope :sort_by_favorites, -> {
    left_joins(:favorites)
      .group(:id)
      .order(Arel.sql('COUNT(favorites.id) DESC'))
  }


  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

    def self.looks(search, word)
    if search == "perfect_match"
      Book.where("title LIKE ?", "#{word}")
    elsif search == "forward_match"
      Book.where("title LIKE ?", "#{word}%")
    elsif search == "backward_match"
      Book.where("title LIKE ?", "%#{word}")
    elsif search == "partial_match"
      Book.where("title LIKE ?", "%#{word}%")
    else
      Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :ensure_correct_user,
only: [:edit, :update, :destroy]

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path, notice:
      "権限がありません"
    end
  end

  def show
    @book = Book.find(params[:id])
    unless ViewCount.exists?(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    if params[:sort] == "new"
      @books = Book.created_within_week.order(created_at: :desc)
    elsif params[:sort] == "high_rate"
      @books = Book.created_within_week.order(rate: :desc)
    elsif params[:sort] == "favorite"
      @books = Book.created_within_week.sort_by_favorites
    else
      @books = Book.created_within_week
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_tag
    @user = current_user
    @book_new = Book.new
    @tag = params[:tag]
    @books = Book.tagged_with(@tag)
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :tag_list)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<div id="favorite-button-<%= book.id %>">
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" style="color: red;"></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post,remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

 <%= book.favorites.count %>
</div>
 

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <%= render 'layouts/errors', obj:book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :rate, "Rate" %><br>
    <div id="post_raty"></div>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tag" %><br>
    <%= f.text_field :tag_list, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><% book.tag_list.each do |tag| %><%= link_to tag,search_tag_path(tag: tag), class:"text-decoration-none me-2" %>
            <% end %></td>
          <td style="white-space: nowrap; vertical-align: middle;">
            <div id="favorite-button-<%= book.id %>" style="display: inline-block;">
            <%= render 'books/favorite', book: book %>
            </div>
            <span style="margin-left: 6px;">
        コメント数: <%= book.book_comments.count %></span>
           <div id="show-star-rate-<%= book.id %>" data-score="<%= book.rate %>" style="display: inline-block;margin-left: 6px;"></div>
           閲覧数: <%= book.view_counts.count %>
          </td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search.html.erb
<% if user_signed_in? %>
      <div class="d-flex justify-content-center mt-3 mb-3">

    <%= form_with(url: search_path, method: :get, local: true, class: "d-flex me-3") do |form| %>
    <%= form.text_field :word, placeholder: "検索ワード", class: "form-control me-2" %>
    <%= form.select(:range, ["User","Book"],{}, { class: "form-select me-2"}) %>
    <%= form.select(:search, [["完全一致", "perfect_match"],["前方一致","forward_match"], ["後方一致","backward_match"],["部分一致","partial_match"]], {}, {class: "form-select me-2" }) %>
    <%= form.submit "検索", class: "btn btn-outline-dark" %>
  <% end %>
  
      <%= form_tag(search_tag_path, method: :get, class: "form-inline") do %>
        <%= text_field_tag :tag, params[:tag], placeholder: "タグ検索", class: "form-control me-2" %>
        <%= submit_tag "タグ検索", class: "btn btn-outline-dark" %>
      <% end %>

    </div>
    <% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

      <%= render 'layouts/errors', obj:@book %>

  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>

      <h2>Books</h2>

      <div class="mb-3">
        <%= link_to '新しい順',
        books_path(sort: 'new'), class: "btn btn-outline-primary btn-sm mr-2" %>
        <%= link_to '評価の高い順',
        books_path(sort: 'high_rate'), class: "btn btn-outline-primary btn-sm mr-2" %>
        <%= link_to 'いいね順',
        books_path(sort: "favorite"), class: "btn btn-outline-primary btn-sm" %>
      </div>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/search_tag.html.erb
<h2>Books search for "<%= params[:tag] %>"</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %><br>
            <span style="font-size:12px;white-space:nowrap;"><%= book.user.name %></span>
            <% end %>
          </td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.body %></td>
        <td><% book.tag_list.each do |tag| %><%= link_to tag,search_tag_path(tag: tag), class:"text-decoration-none me-2" %>
            <% end %>
        </td>
        <td><%= render 'books/favorite', book: book %>いいね
            <span style="margin-left: 6px;">
        コメント数: <%= book.book_comments.count %></span>
        </td>
        <td>
          <div id="show-star-rate-<%= book.id %>" data-score="<%= book.rate %>"></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user:@book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table align-middle'>
  		  <tr>
          <td style="width:70px;"><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <span style="font-size: 12px; white-space: nowrap;"><%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= @book.tag_list.join(',') %></td>
          <td style="white-space: nowrap; vertical-align: middle;">
            <span style="display: inline-block; margin-right: 6px;">
              <%= render 'books/favorite', book: @book %>
            </span>
            <span style="margin-right: 6px;">
          コメント数: <%= @book.book_comments.count %>
            </span>
          <div id="show-star-rate-<%= @book.id %>" 
              class="mr-3"
              data-score="<%= @book.rate %>"
              style="display: inline-block;">
          </div>

          閲覧数: <%= @book.view_counts.count %>

          <% if @book.user == current_user %>
            <%= link_to "Edit",
          edit_book_path(@book), class: "btn btn-success" %>&nbsp
          <%= link_to "Destroy",
          book_path(@book), method: :delete, class: "btn btn-danger", date: { confirm: "本当に削除しますか？" } %>
          <% end %>
          </td>
    </div>
          </td>
        </tr>
      </table>
        <div class="comments-area">
          <%= render 'book_comments/comments', book: @book %>
        </div>

        <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>

  </div>
</div>