config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users
    resources :rooms,only: [:create, :show]
    resources :messages, only: [:create]
    root to: "homes#top"
    get "home/about"=>"homes#about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships,only: [:create, :destroy]
    get 'followings' => 'users#followings', as: 'followings'
    get 'followers' => 'users#followers', as: 'followers'
  end
   get "search" => "searches#search"
   get 'search_tag' => 'books#search_tag'
    
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    @search = params[:search]

    if @range == "User"
       @users = User.looks(@search,@word)
    else
      @books = Book.looks(@search,@word)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<h2>Books search for "<%= params[:word] %>"</h2>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% if @range == "User" %>
      <% @users.each do |user| %>
        <tr>
          <td><% if user.get_profile_image.present? %>
                <%= image_tag user.get_profile_image, size:"50x50", class: "rounded-circle" %>
              <% end %>
              <%= link_to user.name, user_path(user.id) %>
          </td>
          <td>-</td>
          <td><%= user.introduction %></td>
        </tr>
      <% end %>
    <% else %>
      <% @books.each do |book| %>
        <tr>
          <td><% if book.user.get_profile_image.present? %>
                <%= image_tag book.user.get_profile_image, size:"50x50", class: "rounded-circle" %>
              <% end %>
              <%= link_to book.user.name, user_path(book.user) %>
          </td>
          <td><%= link_to book.title, book_path(book) %></td>
           <td><%= book.body %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>